# Generated by Django 6.0 on 2026-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Seen', 'Seen'), ('Approved', 'Approved by Company'), ('Rejected', 'Rejected'), ('Selected', 'Selected by Student')], default='Waiting', max_length=20),
        ),
    ]
