# Generated by Django 6.0 on 2026-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Чакащи..'), ('Seen', 'Видяно'), ('Approved', 'Одобрен'), ('Rejected', 'Отхвърлен'), ('Selected', 'Избрано от Студент')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='internoffer',
            name='field',
            field=models.CharField(choices=[('IT', 'ИТ'), ('Marketing', 'Маркетинг'), ('Finance', 'Финанси')], max_length=50),
        ),
        migrations.AlterField(
            model_name='internoffer',
            name='salary_type',
            field=models.CharField(choices=[('Paid', 'Платен'), ('Unpaid', 'Неплатен')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internoffer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Чернова'), ('ACTIVE', 'Активна'), ('CLOSED', 'Затворена')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='internoffer',
            name='workspace_type',
            field=models.CharField(choices=[('Onsite', 'Присъствено'), ('Remote', 'Дистанционно'), ('Hybrid', 'Хибридно')], max_length=20),
        ),
    ]
