# Generated by Django 6.0 on 2026-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='internoffer',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
