# Generated by Django 6.0 on 2026-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_internoffer_benefits_internoffer_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation_letter',
            field=models.TextField(blank=True),
        ),
    ]
