# Generated by Django 6.0 on 2026-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_application_cv_text_alter_application_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internoffer',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
