# Generated by Django 6.0 on 2026-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_internoffer_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_file',
            field=models.FileField(blank=True, null=True, upload_to='motivation_letters/'),
        ),
    ]
