# Generated by Django 6.0 on 2026-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_application_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company_status',
            field=models.CharField(choices=[('PENDING', 'Чака одобрение'), ('APPROVED', 'Одобрен'), ('REJECTED', 'Върнат за корекция')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='mentor_status',
            field=models.CharField(choices=[('PENDING', 'Чака одобрение'), ('APPROVED', 'Одобрен'), ('REJECTED', 'Върнат за корекция')], default='PENDING', max_length=20),
        ),
    ]
