# Generated by Django 6.0 on 2026-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_report_company_status_report_mentor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Чакащи..'), ('Seen', 'Видяно'), ('Approved', 'Одобрен'), ('Offer', 'Оферта'), ('Rejected', 'Отхвърлен'), ('RejectedByStudent', 'Отхвърлено от студента'), ('Selected', 'Избрано от Студент')], default='Waiting', max_length=20),
        ),
    ]
