# Generated by Django 6.0 on 2026-05-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_mentorstudentremovalreason'),
        ('internships', '0011_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('task', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Чернова'), ('SUBMITTED', 'Изпратен')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internships.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
