# Generated by Django 6.0 on 2026-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_internshipdailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company_eik',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='internship_track',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='mentor_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='mentor_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
