# Generated by Django 6.0 on 2026-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='company',
            name='career',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
