# Generated by Django 6.0 on 2026-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_banner_company_career_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image_url',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
