# Generated by Django 6.0 on 2026-02-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_specialty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='academics.department'),
            preserve_default=False,
        ),
    ]
