# Generated by Django 6.0 on 2026-03-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_specialty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
