# Generated by Django 6.0 on 2026-04-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_student_faculty_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorStudentRemovalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_removal_reasons', to='academics.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_removal_reasons', to='academics.student')),
            ],
            options={
                'verbose_name': 'Причина за премахване на студент',
                'verbose_name_plural': 'Причини за премахване на студенти',
                'ordering': ('-removed_at',),
            },
        ),
    ]
